### ISSUE TITLE
大佬注册新TG号了吗？我把你拉回pyramid群组。

### ISSUE THREAD

**Issue by lm317379829** [UndCover/PyramidStore#24]
大佬注册新TG号了吗，我把你拉回pyramid群组。
影视的作者FongMi，在逐步把你的pyramid集成到影视apk中，我们也有个小群组，要不要一起来交流交流？
https://github.com/FongMi/TV

**Comment by UndCover** [comment]
好，等我找找账号先

**Comment by lm317379829** [comment]
> 好，等我找找账号先

被注销了好像就找不回来了，要重新注册。

**Comment by UndCover** [comment]
> > 好，等我找找账号先
> 
> 被注销了好像就找不回来了，要重新注册。

我是密码忘记了，应该没有注销
