### ISSUE TITLE
FongMi/TV修改后编译报错

### ISSUE THREAD

**Issue by lm317379829** [UndCover/PyramidStore#9]
FongMi/TV：https://github.com/FongMi/TV
修改参照：https://github.com/UndCover/PyramidStore/blob/main/tutorial.md
1、2、3、4不变，5中
app/src/main/java/com/fongmi/android/tv/api/**ApiConfig.java**：
**PythonLoader.getInstance().setConfig(jsonStr);**改为
**PythonLoader.getInstance().setConfig(Prefers.getUrl(),object.toString());**
余下两条根据源码差别，将其中**SourceBean sourceBean**改为**Site site**
编译报错，信息如下：
> Task :exoplayer-extension-ima:extractReleaseAnnotations
WARNING: [Processor] Library '/home/runner/.gradle/caches/modules-2/files-2.1/com.google.ads.interactivemedia.v3/interactivemedia/3.26.0/2583e7eb3c63bcee42b830dc3776dc96b8a86a7f/interactivemedia-3.26.0.jar' contains references to both AndroidX and old support library. This seems like the library is partially migrated. Jetifier will try to rewrite the library anyway.
 Example of androidX reference: 'androidx/annotation/Nullable'
 Example of support library reference: 'android/support/annotation/Nullable'
/home/runner/work/TVBoxDIY/TVBoxDIY/TV/app/src/main/java/com/fongmi/android/tv/api/ApiConfig.java:192: error: illegal start of type

                return PythonLoader.getInstance().proxyLocal(<?, ?>,param);
                                                              ^
/home/runner/work/TVBoxDIY/TVBoxDIY/TV/app/src/main/java/com/fongmi/android/tv/api/ApiConfig.java:192: error: illegal start of expression
                return PythonLoader.getInstance().proxyLocal(<?, ?>,param);
> Task :app:compileLeanbackReleaseJavaWithJavac FAILED
                                                               ^
/home/runner/work/TVBoxDIY/TVBoxDIY/TV/app/src/main/java/com/fongmi/android/tv/api/ApiConfig.java:192: error: illegal start of expression
                return PythonLoader.getInstance().proxyLocal(<?, ?>,param);
                                                                 ^
/home/runner/work/TVBoxDIY/TVBoxDIY/TV/app/src/main/java/com/fongmi/android/tv/api/ApiConfig.java:192: error: illegal start of expression
                return PythonLoader.getInstance().proxyLocal(<?, ?>,param);
                                                                  ^
/home/runner/work/TVBoxDIY/TVBoxDIY/TV/app/src/main/java/com/fongmi/android/tv/api/ApiConfig.java:192: error: illegal start of expression
                return PythonLoader.getInstance().proxyLocal(<?, ?>,param);
                                                                   ^
/home/runner/work/TVBoxDIY/TVBoxDIY/TV/app/src/main/java/com/fongmi/android/tv/api/ApiConfig.java:197: error: illegal start of type
            if(doStr.equals("live")) return PythonLoader.getInstance().proxyLocal(<?, ?>,param);
                                                                                   ^
/home/runner/work/TVBoxDIY/TVBoxDIY/TV/app/src/main/java/com/fongmi/android/tv/api/ApiConfig.java:197: error: illegal start of expression
            if(doStr.equals("live")) return PythonLoader.getInstance().proxyLocal(<?, ?>,param);
                                                                                    ^
/home/runner/work/TVBoxDIY/TVBoxDIY/TV/app/src/main/java/com/fongmi/android/tv/api/ApiConfig.java:197: error: illegal start of expression
            if(doStr.equals("live")) return PythonLoader.getInstance().proxyLocal(<?, ?>,param);
                                                                                      ^
/home/runner/work/TVBoxDIY/TVBoxDIY/TV/app/src/main/java/com/fongmi/android/tv/api/ApiConfig.java:197: error: illegal start of expression
            if(doStr.equals("live")) return PythonLoader.getInstance().proxyLocal(<?, ?>,param);
                                                                                       ^
/home/runner/work/TVBoxDIY/TVBoxDIY/TV/app/src/main/java/com/fongmi/android/tv/api/ApiConfig.java:197: error: illegal start of expression
            if(doStr.equals("live")) return PythonLoader.getInstance().proxyLocal(<?, ?>,param);
                                                                                        ^
10 errors

556 actionable tasks: 425 executed, 131 from cache
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileLeanbackReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by UndCover** [comment]
public Object[] proxyLocal(Map<?, ?> param) {
    //pyramid-add-start
    try {
        if(param.containsKey("api")){
            String doStr = param.get("do").toString();
            if(doStr.equals("ck"))
                return PythonLoader.getInstance().proxyLocal("","",param);
            Site site = getSite(doStr);
            return PythonLoader.getInstance().proxyLocal(site.getKey(), site.getExt(), param);
        }else{
            String doStr = param.get("do").toString();
            if(doStr.equals("live")) return PythonLoader.getInstance().proxyLocal("","",param);
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
    //pyramid-add-end
    return loader.proxyInvoke(param);
}
